language: ruby

rvm:
  - "2.3"
  - "2.4"
  - "2.5"

cache: bundler

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test

notifications:
  email: false